server:
  port: 7070

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: cx982508546.
    url: jdbc:mysql://localhost:3306/database_?serverTimezone=GMT%2b8
    username: root
